## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

theme = "blog-story"
languageCode = 'en-us'
title = 'Welcome to this #WAIQ Age'
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
baseURL = "/"
publishDir = "public"

# Remote
#baseURL = "https://caressofsteel.github.io/demos/hugo/hugo-story/"
#publishDir = "//centos/sites/hugodev/hugostory/"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

#disableKinds = ["taxonomy", "section"]
disableKinds = ["section"]
ignoreLogs = ['warning-goldmark-raw-html']

## -----------------------------------------------
## Analytics support
## -----------------------------------------------

#googleAnalytics: G-MEASUREMENT_ID
#swetrixAnalytics = "3UYKaHJP56by"

## -----------------------------------------------
## Taxonomies
## -----------------------------------------------

[taxonomies]
topic = "topics"
area = "areas"
#category = "categories"

[related]
  includeNewer = true
  threshold = 80
  toLower = true

  [[related.indices]]
    name = "title"
    weight = 30

  [[related.indices]]
    name = "description"
    weight = 30

  [[related.indices]]
    name = "areas"
    weight = 10

  [[related.indices]]
    name = "topics"
    weight = 30

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]

[Params.social]
  #github = "https://github.com/caressofsteel/"
  #twitter = "https://twitter.com/caressofsteel_"
  email = "hello@waiq.technology"
  #instagram = "https://instagram.com"
  linkedin = "https://linkedin.com"
  #telegram = "https://telegram.org"

[Params.asset]
additional_css = ["/css/fontawesome-all.min.css","/css/waiq.css"]
additional_js = ["/js/fontawesome-all.min.js","/js/waiq.js"]

## -----------------------------------------------
## Languages support
## -----------------------------------------------
[languages]

[languages.en]
  languageName = "English"
  weight = 1
  contentDir = "content/en"

[languages.es]
  languageName = "Espa√±ol"
  weight = 2
  contentDir = "content/es"
